// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/flashbacks/api-service/internal/infrastructure/di"
	"github.com/flashbacks/api-service/internal/interfaces/handler"
)

// Injectors from wire.go:

// InitializeApp builds the complete application dependency graph using Wire.
// The implementation is generated into wire_gen.go.
func InitializeApp() (*App, error) {
	appConfig := di.ProvideConfig()
	db, err := di.ProvideDB(appConfig)
	if err != nil {
		return nil, err
	}
	scanManager := di.ProvideScanManager(db, appConfig)
	client := di.ProvideOcrClient(appConfig)
	ocrManager := di.ProvideOcrManager(db, client, appConfig)
	llmOcrService := di.ProvideLlmOcrService(db)
	config := di.ProvideThumbnailConfig(db, appConfig)
	thumbnailProvider := di.ProvideThumbnailProvider(config)
	nominatimClient := di.ProvideNominatimClient()
	geolocationService := di.ProvideGeolocationService(db, nominatimClient)
	exifClient := di.ProvideExifClient(appConfig)
	backgroundSyncManager := di.ProvideBackgroundSyncManager(db, thumbnailProvider, geolocationService, exifClient)
	float64_2 := di.ProvideMaxMegapixels(appConfig)
	tagScanManager := di.ProvideTagScanManager(db, llmOcrService, float64_2)
	embeddingBackfillManager := di.ProvideEmbeddingBackfillManager(db)
	thumbnailBatch := di.ProvideThumbnailBatch(thumbnailProvider)
	clusterStorage := di.ProvideClusterStorage()
	galleryAccess := di.ProvideGalleryAccess(db)
	settingsLoader := di.ProvideSettingsLoader(db)
	llmFactory := di.ProvideLLMFactory(db, float64_2)
	fileMover := di.ProvideFileMover(db)
	i18nService, err := di.ProvideI18nService()
	if err != nil {
		return nil, err
	}
	string2 := di.ProvideExifBackupDir(db)
	exifAgent := di.ProvideExifAgent(appConfig, string2)
	flashbacksMCPServer := di.ProvideMCPServer(db, llmFactory, llmOcrService, float64_2, embeddingBackfillManager, exifAgent)
	conversationService := di.ProvideConversationService(db)
	agentConfig := di.ProvideAgentConfig(appConfig)
	agent := di.ProvideAgent(conversationService, flashbacksMCPServer, agentConfig)

	// Repositories
	imageFileRepo := di.ProvideImageFileRepo(db)
	galleryFolderRepo := di.ProvideGalleryFolderRepo(db)
	llmRepo := di.ProvideLlmRepo(db)
	metadataRepo := di.ProvideMetadataRepo(db)
	ocrRepo := di.ProvideOcrRepo(db)
	imageTagRepo := di.ProvideImageTagRepo(db)
	appSettingsRepo := di.ProvideAppSettingsRepo(db)
	userSettingsRepo := di.ProvideUserSettingsRepo(db)
	syncHistoryRepo := di.ProvideSyncHistoryRepo(db)

	serverDeps := handler.ServerDeps{
		DB:                  db,
		Config:              appConfig,
		ScanManager:         scanManager,
		OcrManager:          ocrManager,
		LlmOcrService:       llmOcrService,
		BackgroundSync:      backgroundSyncManager,
		TagScanManager:      tagScanManager,
		EmbeddingBackfill:   embeddingBackfillManager,
		ThumbnailProvider:   thumbnailProvider,
		ThumbnailBatch:      thumbnailBatch,
		OcrClient:           client,
		ClusterStorage:      clusterStorage,
		GalleryAccess:       galleryAccess,
		SettingsLoader:      settingsLoader,
		LlmFactory:          llmFactory,
		FileMover:           fileMover,
		I18n:                i18nService,
		GeolocationService:  geolocationService,
		Nominatim:           nominatimClient,
		McpServer:           flashbacksMCPServer,
		Agent:               agent,
		AgentConfig:         agentConfig,
		ConversationService: conversationService,
		ExifClient:          exifClient,
		ImageFileRepo:       imageFileRepo,
		GalleryFolderRepo:   galleryFolderRepo,
		LlmRepo:             llmRepo,
		MetadataRepo:        metadataRepo,
		OcrRepo:             ocrRepo,
		ImageTagRepo:        imageTagRepo,
		AppSettingsRepo:     appSettingsRepo,
		UserSettingsRepo:    userSettingsRepo,
		SyncHistoryRepo:     syncHistoryRepo,
	}
	server := di.ProvideServer(serverDeps)
	loginRateLimiter := di.ProvideLoginRateLimiter()
	sessionConfig := di.ProvideSessionConfig(appConfig)
	sessionRepository := di.ProvideSessionRepository(db, sessionConfig)
	sessionCleanupJob := di.ProvideSessionCleanupJob(sessionRepository)
	bootstrapService := di.ProvideBootstrapService(db, appConfig)
	authService := di.ProvideAuthService(db, bootstrapService, sessionRepository, loginRateLimiter)
	authMiddleware := di.ProvideAuthMiddleware(sessionRepository, authService, i18nService)
	csrfProtection := di.ProvideCSRFProtection(i18nService)
	userService := di.ProvideUserService(db, sessionRepository)
	authHandlers := di.ProvideAuthHandlers(authService, bootstrapService, userService, sessionRepository, db, i18nService)
	app := &App{
		DB:                db,
		Config:            appConfig,
		Server:            server,
		ScanManager:       scanManager,
		OcrManager:        ocrManager,
		LlmOcrService:     llmOcrService,
		BackgroundSync:    backgroundSyncManager,
		TagScanManager:    tagScanManager,
		EmbeddingBackfill: embeddingBackfillManager,
		ThumbnailService:  thumbnailProvider,
		LoginLimiter:      loginRateLimiter,
		SessionCleanup:    sessionCleanupJob,
		AuthMiddleware:    authMiddleware,
		CSRFProtection:    csrfProtection,
		AuthHandlers:      authHandlers,
	}
	return app, nil
}
